version: "3"

networks:
  payment-test-network:
    driver: overlay
    driver_opts:
      encrypted: 'true'
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  redis:
    image: redis:3.0
    ports:
      - "6379"
    networks:
      - payment-test-network
    # deploy:
    #   replicas: 2
    #   update_config:
    #     parallelism: 2
    #     delay: 10s
    #   restart_policy:
    #     condition: on-failure

  db:
    image: mysql:5.7
    ports:
          - "3306:3306"
    volumes:
      - "payment-test-mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - payment-test-network
    deploy:
      placement:
        constraints: [node.role == manager]

  web:
    build:
      context: ./
      dockerfile: env/docker/app.dockerfile
    depends_on:
      - redis
      - db
    volumes:
      - ./:/www
      - ./env/docker/crontab:/etc/crontabs/docker
    working_dir: /www
    environment:
      - ENVIRONMENT=local
      - PHP_IDE_CONFIG=serverName=payment-test.local
      - OPCACHE_VALIDATE_TIMESTAMPS=true
      - OPCACHE_REVALIDATE_FREQ=2
      - XDEBUG_ENABLE=true
      - DB_HOST=db
      - DB_DATABASE=payment_test_dev
      - DB_USER=root
      - DB_PASSWORD=root
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=async
      - DB_COLLATION=utf8_general_ci
    networks:
      - payment-test-network
    # deploy:
    #   replicas: 3
    #   update_config:
    #     parallelism: 2
    #   restart_policy:
    #     condition: on-failure
    extra_hosts:
      - "staging-oms-graylog.chaordicsystems.com:172.29.7.61"

  nginx:
    image: nginx:1.10
    working_dir: /www
    volumes:
      - ./env/docker/web.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
    ports:
      - "80:80"
      # - "443:443"
    networks:
      - payment-test-network


networks:
  payment-test-network:

volumes:
  payment-test-mysql:

